FROM rust:1.92.0-alpine3.22 AS test-runner

RUN rustup target add wasm32-unknown-unknown

RUN cargo install wasm-bindgen-cli --version 0.2.120
RUN cargo install geckodriver --version 0.36.0

RUN apk add firefox

COPY . .
RUN cargo test -p otlsp-client -p luct-otlsp -p luct-client -p luct-extension --locked --target wasm32-unknown-unknown