[package]
name = "luct-client"
description = "Client library to fetch and validate certificate transparency logs"
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = { workspace = true }
publish = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }

[dependencies]
luct-core = { version = "0.2.2", path = "../luct-core" }

reqwest = { workspace = true, optional = true }
url = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }

thiserror = { workspace = true }
tracing = { workspace = true }

futures = { workspace = true }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
rustls-rustcrypto = { workspace = true }

[dev-dependencies]
luct-test = { version = "0.2.2", path = "../luct-test" }

tokio = { workspace = true, features = ["rt", "macros"] }

# This needs to be imported here to set the "js" feature,
# otherwise the crate would not compile to wasm
getrandom = { version = "0.4", features = ["wasm_js"] }
old_getrandom = { package = "getrandom", version = "0.2", features = ["js"] }

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]
