name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  
  build-cli:
    needs:
      - tests
    uses: ./.github/workflows/cli.yml

  build-node:
    needs:
      - tests
    uses: ./.github/workflows/node.yml

  build-extension:
    needs:
      - tests
    uses: ./.github/workflows/extensions.yml