name: Tests
on: [push, pull_request, workflow_call]

jobs: 
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        platform:
          - name: Linux X86-64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_ext: ""
            use_cross: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: 1.92.0
            targets: ${{ matrix.platform.target }}

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v5
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v5
        with:
          path: target
          key: ${{ runner.os }}-cargo-test-target-${{ matrix.platform.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build CLI tool (native)
        if: ${{ !matrix.platform.use_cross }}
        run: cargo test --locked --target ${{ matrix.platform.target }}

